model_list:
  # === Google models ===
  - model_name: gemini-2.5-pro
    litellm_params:
      model: gemini/gemini-2.5-pro
 

  - model_name: gemini-2.5-flash
    litellm_params:
      model: gemini/gemini-2.5-flash
 

  - model_name: gemini-1.5-pro
    litellm_params:
      model: gemini/gemini-1.5-pro
 

  - model_name: gemini-1.5-flash
    litellm_params:
      model: gemini/gemini-1.5-flash
 

  - model_name: gemini-1.5-flash-8b
    litellm_params:
      model: gemini/gemini-1.5-flash-8b
 

  # --- optional
  - model_name: gemini-1.5-pro-latest
    litellm_params:
      model: gemini/gemini-1.5-pro-latest
 

  - model_name: gemini-1.5-flash-latest
    litellm_params:
      model: gemini/gemini-1.5-flash-latest
 

  - model_name: gemini-2.5-pro-preview-06-05
    litellm_params:
      model: gemini/gemini-2.5-pro-preview-06-05
 

  - model_name: gemini-2.5-flash-preview-05-20
    litellm_params:
      model: gemini/gemini-2.5-flash-preview-05-20
 

  # --- Embeddings (use this for RAG) ---
  - model_name: text-embedding-004
    litellm_params:
      model: gemini/text-embedding-004
 
 
  # (Optional legacy/extra embedding
  - model_name: gemini-embedding-001
    litellm_params:
      model: gemini/gemini-embedding-001
 

  # --- (Optional) Gemma via AI Studio (chat) ---
  - model_name: gemma-3-27b-it
    litellm_params:
      model: gemini/gemma-3-27b-it

  # === Anthropic Claude models ===
  - model_name: claude-sonnet-4-5
    litellm_params:
      model: anthropic/claude-sonnet-4-5-20250929

  - model_name: claude-opus-4-1
    litellm_params:
      model: anthropic/claude-opus-4-1-20250805

  - model_name: claude-opus-4
    litellm_params:
      model: anthropic/claude-opus-4-20250514

  - model_name: claude-sonnet-4
    litellm_params:
      model: anthropic/claude-sonnet-4-20250514

  - model_name: claude-3-7-sonnet
    litellm_params:
      model: anthropic/claude-3-7-sonnet-20250219

  - model_name: claude-3-5-sonnet-new
    litellm_params:
      model: anthropic/claude-3-5-sonnet-20241022

  - model_name: claude-3-5-haiku
    litellm_params:
      model: anthropic/claude-3-5-haiku-20241022

  - model_name: claude-3-5-sonnet-old
    litellm_params:
      model: anthropic/claude-3-5-sonnet-20240620

  - model_name: claude-3-haiku
    litellm_params:
      model: anthropic/claude-3-haiku-20240307

  - model_name: claude-3-opus
    litellm_params:
      model: anthropic/claude-3-opus-20240229

# === DeepSeek models ===
  - model_name: deepseek-chat
    litellm_params:
      model: deepseek/deepseek-chat

  - model_name: deepseek-reasoner
    litellm_params:
      model: deepseek/deepseek-reasoner
      